In [2]:
import numpy as np 
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sb

In [3]:
df = pd.read_csv('C:\\Users\\Parul\\Desktop\\DATASETS\\insurance_data.csv')

In [4]:
df.head()

age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

In [5]:
x = df.age.values #df['age'].values
y = df.bought_insurance.values

## Train Test Split

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
#Split it to 10% testing and remaining trainin
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1)

In [8]:
x_test

array([46, 29, 18], dtype=int64)

In [9]:
y_test

array([1, 0, 0], dtype=int64)

In [10]:
x_train

array([27, 45, 40, 61, 26, 18, 62, 60, 52, 47, 55, 25, 28, 56, 55, 22, 58,
       54, 49, 23, 21, 25, 50, 19], dtype=int64)

In [11]:
y_train

array([0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0], dtype=int64)

## K-Folds Cross Validation

In [12]:
from sklearn.model_selection import KFold
import numpy as np

In [14]:
#For insurance dataset
kf = KFold(10) #means 10 times it will test your data
for train, test in kf.split(x):
    print('train: %s, test: %s' %(x[train],x[test]))

train: [52 46 56 55 60 62 61 18 28 27 29 49 55 25 58 19 18 21 26 40 45 50 54 23], test: [22 25 47]
train: [22 25 47 55 60 62 61 18 28 27 29 49 55 25 58 19 18 21 26 40 45 50 54 23], test: [52 46 56]
train: [22 25 47 52 46 56 61 18 28 27 29 49 55 25 58 19 18 21 26 40 45 50 54 23], test: [55 60 62]
train: [22 25 47 52 46 56 55 60 62 27 29 49 55 25 58 19 18 21 26 40 45 50 54 23], test: [61 18 28]
train: [22 25 47 52 46 56 55 60 62 61 18 28 55 25 58 19 18 21 26 40 45 50 54 23], test: [27 29 49]
train: [22 25 47 52 46 56 55 60 62 61 18 28 27 29 49 19 18 21 26 40 45 50 54 23], test: [55 25 58]
train: [22 25 47 52 46 56 55 60 62 61 18 28 27 29 49 55 25 58 26 40 45 50 54 23], test: [19 18 21]
train: [22 25 47 52 46 56 55 60 62 61 18 28 27 29 49 55 25 58 19 18 21 45 50 54
 23], test: [26 40]
train: [22 25 47 52 46 56 55 60 62 61 18 28 27 29 49 55 25 58 19 18 21 26 40 54
 23], test: [45 50]
train: [22 25 47 52 46 56 55 60 62 61 18 28 27 29 49 55 25 58 19 18 21 26 40 45
 50], test: [54 23]
